repos:
  - repo: local
    hooks:
      - id: docker-build
        name: docker build (may take a minute)
        entry: .pre-commit/hooks/docker-build.sh
        language: system
        files: '^.+\.(go|mod|sum)'
        pass_filenames: false
        verbose: true