version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.4.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  search-service:
    build: .
    container_name: search-service
    environment:
      - OPENSEARCH_ENDPOINT=http://opensearch:9200
      - PORT=8080
      - ENV=local
    ports:
      - "8080:8080"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  react-app:
    build:
      context: ./frontend/search-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3001:3000"
    depends_on:
      - search-service
    networks:
      - opensearch-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - opensearch-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - opensearch-net

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge

volumes:
  grafana-storage: