{
 "title": "Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}